### ISSUE TITLE
NullBot Random message

### ISSUE THREAD

**Issue by Maja0426** [david-szabo97/null-volgy-null-bot#1]
### "Ne packázz velem, Skynet az uncsitesóm!" - NullBot

A feladat egyszerű. Olyan mondatokra, melyekben bizonyos szavak előfordulnak, a bot véletlenszerű, vicces válaszokat ad, melyeknek nyilván semmi köze sincs a kérdéshez. Nem bonyolítanám túl, a random válaszok egy array-ban tárolódnak, ha pedig az msg.content tartalmaz bizonyos szót vagy akár szavakat, az msg.reply meghív egy függvényt ami generálja a véletlenszerű válaszokat. Hirtelen ennyi. 

ui.: Bocsi ha gány az issue, mindig egyedül dolgoztam, szóval ez az első...

**Comment by david-szabo97** [comment]
Szia az én részemről rendben van!
"random-messages" néven készítheted a plugint :) Várom a Pull Request-et, ott folytatjuk ;)
