### ISSUE TITLE
Random ChuckNorris joke through API

### ISSUE THREAD

**Issue by david-szabo97** [david-szabo97/null-volgy-null-bot#3]
Create a plugin that fetches a random joke from the free chuck norris API. It should work by sending `!chucknorris` message into any channel. Bot should answer in the same channel the message was sent.

API: https://api.chucknorris.io/
MessageEmbed reference: https://discord.js.org/#/docs/main/stable/class/MessageEmbed
MessageEmbed example: https://discord.js.org/#/docs/main/stable/examples/embed

**Comment by Maja0426** [comment]
Nincs túl nagy tumultus, úgyhogy lehet még ezt bevállalnám...

**Comment by david-szabo97** [comment]
@Maja0426 Várom 👍

**Comment by david-szabo97** [comment]
PR: #6
